update invoice calculations
src/components/agency-module/booking-invoice-items-table.tsx:198:16 - error TS2551: Property 'totalBookFinalValue' does not exist on type 'BookingInvoiceDetailDTO'. Did you mean 'totalBookValue'?

198           item.totalBookFinalValue ?? discountAfterValue
                   ~~~~~~~~~~~~~~~~~~~

  src/types/invoice.ts:31:3
    31   totalBookValue: number
         ~~~~~~~~~~~~~~
    'totalBookValue' is declared here.

src/components/agency-module/booking-invoice-items-table.tsx:340:48 - error TS2551: Property 'totalBookFinalValue' does not exist on type 'BookingInvoiceDetailDTO'. Did you mean 'totalBookValue'?

340           totalBookFinalValue: safeNumber(item.totalBookFinalValue),
                                                   ~~~~~~~~~~~~~~~~~~~

  src/types/invoice.ts:31:3
    31   totalBookValue: number
         ~~~~~~~~~~~~~~
    'totalBookValue' is declared here.

Found 2 errors.